baseURL = "https://study.skkuding.dev"
languageCode = 'ko-kr'
title = 'ìŠ¤ê¾¸ë”© Cookbook'


[module]
[[module.imports]]
path = "github.com/colinwilson/lotusdocs"
disable = false
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
disable = false

[params]
title = 'ìŠ¤ê¾¸ë”© Cookbook ğŸ³'
description = 'ì„±ê· ê´€ëŒ€í•™êµ ì½”ë“œë‹¹ ê°œë°œíŒ€ ìŠ¤ê¾¸ë”©ì˜ ê°œë°œ ë ˆì‹œí”¼'
images = ['open-graph.png']
[params.footer]
copyright = 'Â© :YEAR: SKKUDING. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)'

[params.social]
github = 'skkuding'

[params.docs]
repoURL = 'https://github.com/skkuding/cookbook'
editPage = true
sidebarIcons = true

[menu]
[[menu.primary]]
name = "Infra"
url = "/docs/infra/"
identifier = "docs"
weight = 10

[[menu.primary]]
name = "Backend"
url = "/docs/backend/"
identifier = "showcase"
weight = 20

[[menu.primary]]
name = "Frontend"
url = "/docs/frontend/"
identifier = "community"
weight = 30

[markup.goldmark.renderer]
unsafe = true # raw HTML support

[deployment]
[[deployment.targets]]
name = 'AWS S3'
URL = 's3://study.skkuding.dev?region=ap-northeast-2'
